name: Test Scripts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-scripts:
    name: Test Scripts
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4