name: Test Scripts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-scripts-ubuntu:
    name: Test Scripts Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
          
      - name: Run tests
        run: |
          .\Run-Tests.ps1
        shell: pwsh
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          
  test-scripts-windows:
    name: Test Scripts Windows
    runs-on: windows-latest
    needs: test-scripts-ubuntu
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          .\Run-Tests.ps1
        shell: pwsh
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}