name: Test Scripts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-scripts:
    name: Test Scripts
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Get Cloudflare Zone ID
        run: ./cloudflare/Get-CloudflareZoneId-Test.ps1
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}